apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: analytics-service-ingress
  namespace: analytics-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx # Indica que o AWS Load Balancer Controller deve gerenciar isso
  rules:
    - http:
        paths:
          - path: /analytics-service/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: analytics-service # Nome do Service criado acima
                port:
                  number: 80