apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: analytics-service
type: Opaque
data:
  AWS_DYNAMODB_TABLE: a
  # Base64 encoded 'postgres'
  AWS_ACCESS_KEY_ID: a
  # Base64 encoded 'your_secure_password'
  AWS_SECRET_ACCESS_KEY: a
  AWS_REGION: a
  AWS_SQS_URL: a
  AWS_SQS_ENDPOINT: a

