apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: analytics-service
type: Opaque
data:
  AWS_DYNAMODB_TABLE: 
  AWS_REGION: 
  AWS_SQS_URL: 
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  AWS_SESSION_TOKEN: 


