apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-configmap
  namespace: evaluation-service
data:
  # Example key-value pair
  FLAG_SERVICE_URL: a
  # Example of an entire configuration file content
  TARGETING_SERVICE_URL: a
