apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: evaluation-service
type: Opaque
data:
  REDIS_URL: 
  AWS_SQS_URL: 
  AWS_REGION: 
  SERVICE_API_KEY: 
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  AWS_SESSION_TOKEN: 


