apiVersion: v1
kind: ServiceAccount
metadata:
  name: evaluation-service-account
  namespace: evaluation-service
  annotations:
    # Substitua pelo ARN real da sua LabRole (veja no console IAM)
    eks.amazonaws.com/role-arn: arn:aws:iam::935451498002:role/LabRole